CREATE TABLE IF NOT EXISTS companies (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ticker VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  sector VARCHAR(120),
  status VARCHAR(32) DEFAULT 'pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS filings (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  period VARCHAR(20) NOT NULL,
  total_assets DECIMAL(20,4),
  total_debt DECIMAL(20,4),
  cash_and_equivalents DECIMAL(20,4),
  receivables DECIMAL(20,4),
  interest_income DECIMAL(20,4),
  non_shariah_income DECIMAL(20,4),
  revenue DECIMAL(20,4),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_filings_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  UNIQUE KEY uq_company_period (company_id, period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS articles (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  slug VARCHAR(190) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  body LONGTEXT,
  published_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scholars (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  slug VARCHAR(190) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  bio TEXT,
  credentials TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
